spring:
  mongodb:
    uri: mongodb://mongodb:27017/fitnessdb
  data:
    mongodb:
      database: fitnessdb
      auto-index-creation: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    topic:
      name: activity-events


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/


server:
  port: 8082

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

