spring:
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiService.model.Activity
        spring.json.trusted.packages: "*"

    topic:
      name: activity-events


  mongodb:
    uri: mongodb://localhost:27017/airecommendation
  data:
    mongodb:
      database: airecommendation
      auto-index-creation: true

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 8083
