spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/fitness
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 8081